### ISSUE TITLE
Tango comments <-> rustfmt interaction

### ISSUE THREAD

**Issue by skade** [pnkfelix/tango#9] opened 2016-09-28 13:19 UTC
cargo fmt works quite well with tango because of the bidirectional source mapping, except for one aspect: comments.

There's two issues:

rustfmt will destroy tango comments:

``` rust
//@
```

will become

``` rust
// @
```

It will also destroy these blocks when fixing overlong comment lines:

``` rust
//@ This is a very long line that breaks < here
```

will become

``` rust
// @ This is a very long line that breaks
// < here
```

Breaking the source mapping.

A desired outcome would be that `cargo build && cargo fmt && cargo build` yields a clean tango file.

**Comment by pnkfelix** [comment] 2016-09-28 13:58
I have been thinking more about this since you told me about it on twitter.

I could extend tango to allow whitespace between the `//` and the `@` when it is looking for its special symbol sequence during rust->md conversion, as a hack to deal with the first problem.

The fact that rustfmt will introduce line breaks into long comment lines seems unfortunate. I guess I could change tango so that it will break such lines itself during the md->rust trip, and then reassemble them into a single line during the rust->md trip (by making the follow-on lines have a marker like `//@\` or something)

I am not terribly thrilled with the idea of introducing either change by default, but since the design of tango is that it is invoked as a library function, not a command line executable, it seems like I could just make these choices user-selectable. E.g. put them into options and then perhaps also offer modes like "Max RustFmt Compatibilty" vs "Preserve-Line-Structure".

**Comment by pnkfelix** [comment] 2016-09-28 14:02
(If you ask me, though, I think `rustfmt` should be smarter when it is injecting line breaks. If a series of comments has a wall of trailing characters after each `//`, like this:

```
    //^ Starting line
    //| Here is one line
    //| and another
    //| and another but this one is really long
    //| and a final one
```

then I think it would be more reasonable for `rustfmt` to infer, based on looking at the comment lines immediately above and below, that the author intends for each line to start with `//|`.  (Its not perfect, since it would fail to do the right thing on the first or second line in the example above. But it would be better than what it is doing today.)

**Comment by skade** [comment] 2016-09-28 14:29
Considering that rustfmt rewrites the source completely and stores the orginal comment header, this seems like a feasible option.

https://github.com/rust-lang-nursery/rustfmt/blob/master/src/comment.rs#L23-L56

**Comment by skade** [comment] 2016-09-28 15:28
Feel free to weigh in here: https://github.com/rust-lang-nursery/rustfmt/pull/1179

**Comment by pnkfelix** [comment] 2017-06-07 10:31
Hey @skade is this still an issue, or has `rustfmt` been revised to not redo line-breaking now? I *think* that is a reasonable inference from https://github.com/rust-lang-nursery/fmt-rfcs/issues/17, but I am not sure.

**Comment by Screwtapello** [comment] 2018-05-02 06:28
I can confirm that `rustfmt` no longer messes with the content of comments. It warns about comments that exceed its configured maximum width, but does not re-flow them or break Tango's markers in any way.

**Comment by pnkfelix** [comment] 2018-05-02 07:45
Closing as no longer a significant bug

**Closed by pnkfelix** 2018-05-02 07:45 UTC
Labels: question
